--------------------------------------------------------
--  File created - Tuesday-May-24-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTO_INCREMENT_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "NGAN217"."AUTO_INCREMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TBL_CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NGAN217"."TBL_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TBL_ADMIN
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_ADMIN" 
   (	"ADMIN_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ADMIN_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_BAIVIET
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_BAIVIET" 
   (	"BAIVIET_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENBAIVIET" VARCHAR2(500 BYTE), 
	"TOMTAT" VARCHAR2(1000 BYTE), 
	"NOIDUNG" VARCHAR2(1000 BYTE), 
	"DANHMUCTIN_ID" NUMBER(10,0), 
	"BAIVIET_IMAGE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORY
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_CATEGORY" 
   (	"CATEGORY_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATEGORY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DANHMUC_TIN
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_DANHMUC_TIN" 
   (	"DANHMUCTIN_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENDANHMUC" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DONHANG
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_DONHANG" 
   (	"DONHANG_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SANPHAM_ID" NUMBER(10,0), 
	"SOLUONG" NUMBER(10,0), 
	"MAHANG" VARCHAR2(50 BYTE), 
	"KHACHHANG_ID" NUMBER(10,0), 
	"NGAYTHANG" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TINHTRANG" NUMBER(10,0) DEFAULT 0, 
	"HUYDON" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DONHANG_OLD
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_DONHANG_OLD" 
   (	"DONHANG_ID" NUMBER(10,0), 
	"SANPHAM_ID" NUMBER(10,0), 
	"SOLUONG" NUMBER(10,0), 
	"MAHANG" VARCHAR2(50 BYTE), 
	"KHACHHANG_ID" NUMBER(10,0), 
	"NGAYTHANG" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TINHTRANG" NUMBER(10,0) DEFAULT 0, 
	"HUYDON" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIAODICH
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_GIAODICH" 
   (	"GIAODICH_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SANPHAM_ID" NUMBER(10,0), 
	"SOLUONG" NUMBER(10,0), 
	"MAGIAODICH" VARCHAR2(50 BYTE), 
	"NGAYTHANG" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"KHACHHANG_ID" NUMBER(10,0), 
	"TINHTRANGDON" NUMBER(10,0) DEFAULT 0, 
	"HUYDON" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIAODICH_OLD
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_GIAODICH_OLD" 
   (	"GIAODICH_ID" NUMBER(10,0), 
	"SANPHAM_ID" NUMBER(10,0), 
	"SOLUONG" NUMBER(10,0), 
	"MAGIAODICH" VARCHAR2(50 BYTE), 
	"NGAYTHANG" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"KHACHHANG_ID" NUMBER(10,0), 
	"TINHTRANGDON" NUMBER(10,0) DEFAULT 0, 
	"HUYDON" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIOHANG
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_GIOHANG" 
   (	"KHACHHANG_ID" NUMBER(10,0), 
	"SANPHAM_ID" NUMBER(10,0), 
	"TENSANPHAM" VARCHAR2(100 BYTE), 
	"GIAKHUYENMAI" VARCHAR2(50 BYTE), 
	"SOLUONG" NUMBER(10,0), 
	"IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIOHANG1
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_GIOHANG1" 
   (	"GIOHANG_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TENSANPHAM" VARCHAR2(100 BYTE), 
	"SANPHAM_ID" NUMBER(10,0), 
	"GIASANPHAM" VARCHAR2(50 BYTE), 
	"HINHANH" VARCHAR2(50 BYTE), 
	"SOLUONG" NUMBER(10,0), 
	"KHACHHANG_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIOHANG_OLD
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_GIOHANG_OLD" 
   (	"GIOHANG_ID" NUMBER(10,0), 
	"TENSANPHAM" VARCHAR2(100 BYTE), 
	"SANPHAM_ID" NUMBER(10,0), 
	"GIASANPHAM" VARCHAR2(50 BYTE), 
	"HINHANH" VARCHAR2(50 BYTE), 
	"SOLUONG" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_KHACHHANG
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_KHACHHANG" 
   (	"KHACHHANG_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"NOTE" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"GIAOHANG" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SANPHAM
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_SANPHAM" 
   (	"SANPHAM_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATEGORY_ID" NUMBER(10,0), 
	"SANPHAM_NAME" VARCHAR2(255 BYTE), 
	"SANPHAM_CHITIET" VARCHAR2(255 BYTE), 
	"SANPHAM_MOTA" VARCHAR2(255 BYTE), 
	"SANPHAM_GIA" VARCHAR2(100 BYTE), 
	"SANPHAM_GIAKHUYENMAI" VARCHAR2(100 BYTE), 
	"SANPHAM_ACTIVE" NUMBER(10,0) DEFAULT 1, 
	"SANPHAM_HOT" NUMBER(10,0), 
	"SANPHAM_SOLUONG" NUMBER(10,0), 
	"SANPHAM_IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SLIDER
--------------------------------------------------------

  CREATE TABLE "NGAN217"."TBL_SLIDER" 
   (	"SLIDER_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SLIDER_IMAGE" VARCHAR2(100 BYTE), 
	"SLIDER_CAPTION" CLOB, 
	"SLIDER_ACTIVE" NUMBER(10,0) DEFAULT 1
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("SLIDER_CAPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into NGAN217.TBL_ADMIN
SET DEFINE OFF;
Insert into NGAN217.TBL_ADMIN (ADMIN_ID,EMAIL,PASSWORD,ADMIN_NAME) values (2,'admin@gmail.com','123456','ngan');
REM INSERTING into NGAN217.TBL_BAIVIET
SET DEFINE OFF;
Insert into NGAN217.TBL_BAIVIET (BAIVIET_ID,TENBAIVIET,TOMTAT,NOIDUNG,DANHMUCTIN_ID,BAIVIET_IMAGE) values (5,'Giới thiệu v�? Balo nữ SP11 ','Balo đi h�?c mang phong cách Hàn Quốc sẽ có thiết kế là một ngăn chính rộng rãi để các nàng có thể đựng sách vở thoải mái. Có một ngăn trong và dán cố định để giữ laptop. Các nàng sẽ không phải xách theo túi đựng latop mất công nữa đúng không nào? Quá tiện lợi cho h�?c sinh và sinh viên nhé!

Ngoài ra nó còn có một ngăn trước dạng hộp để bạn đựng các đồ dùng cá nhân như điện thoại, đồ dùng h�?c tập, tai nghe… Với những ai yêu thích sự đơn giản nhưng tiện lợi thì balo này đáp ứng được đi�?u đó.','Chất liệu vải Simili (Vải giả da) nên khá b�?n và không quá cứng. Xu hướng balo đi h�?c hiện nay sẽ thư�?ng có trầm nhẹ nhàng mà cũng tránh để tránh bẩn nữa.',5,'balo2.jpg');
Insert into NGAN217.TBL_BAIVIET (BAIVIET_ID,TENBAIVIET,TOMTAT,NOIDUNG,DANHMUCTIN_ID,BAIVIET_IMAGE) values (6,'Giới thiệu v�? Balo nam SP01','Balo nam th�?i trang cao cấp','Balo sử dụng chất liệu vải Oxford kết hợp với polyester cao cấp giúp balo chống thấm nước tốt, balo b�?n bỉ chắc chắn. Bạn có thể mang balo đi làm, đi h�?c hoặc đi công tác cũng rất phù hợp và không kém phần th�?i trang.

Với ngăn laptop bên trong có lớp mút giúp bảo vệ laptop của bạn tránh bị đập khi mang, bộ đệm lưng siêu thoáng và chống gù theo công nghệ của Âu Mỹ, sử dụng khóa kéo được thiết kế chất liệu cao cấp có tuổi th�? cao',5,'balo1.jpg');
Insert into NGAN217.TBL_BAIVIET (BAIVIET_ID,TENBAIVIET,TOMTAT,NOIDUNG,DANHMUCTIN_ID,BAIVIET_IMAGE) values (7,'Giới thiệu v�? áo thun nữ SP01','�?o thun nữ ','�?o thun nữ th�?i trang năm 2022',4,'download (2).jpg');
Insert into NGAN217.TBL_BAIVIET (BAIVIET_ID,TENBAIVIET,TOMTAT,NOIDUNG,DANHMUCTIN_ID,BAIVIET_IMAGE) values (8,'Giới thiệu v�? áo thun nam SP01','�?o thun nam','�?o thun th�?i trang nam',3,'aothun1.jpg');
REM INSERTING into NGAN217.TBL_CATEGORY
SET DEFINE OFF;
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (17,'�?o thun nữ');
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (18,'�?o thun nam');
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (19,'Quần jean nam');
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (20,'Quần Kaki nam');
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (21,'Balo nam');
Insert into NGAN217.TBL_CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (62,'Balo nữ');
REM INSERTING into NGAN217.TBL_DANHMUC_TIN
SET DEFINE OFF;
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (21,'Giới thiệu v�? các mẫu đồ ngủ ');
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (1,'Giới thiệu các mẫu quần Kaki');
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (2,'Giới thiệu các mẫu quần Jean ');
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (3,'Giới thiệu các mẫu áo thun nam');
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (4,'Giới thiệu các mẫu áo thun nữ');
Insert into NGAN217.TBL_DANHMUC_TIN (DANHMUCTIN_ID,TENDANHMUC) values (5,'Giới thiệu v�? các mẫu Balo th�?i trang năm 2022');
REM INSERTING into NGAN217.TBL_DONHANG
SET DEFINE OFF;
REM INSERTING into NGAN217.TBL_DONHANG_OLD
SET DEFINE OFF;
Insert into NGAN217.TBL_DONHANG_OLD (DONHANG_ID,SANPHAM_ID,SOLUONG,MAHANG,KHACHHANG_ID,NGAYTHANG,TINHTRANG,HUYDON) values (14,21,4,'4236',15,to_timestamp('15-MAY-22 10.58.04.987000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,0);
Insert into NGAN217.TBL_DONHANG_OLD (DONHANG_ID,SANPHAM_ID,SOLUONG,MAHANG,KHACHHANG_ID,NGAYTHANG,TINHTRANG,HUYDON) values (15,20,3,'6503',16,to_timestamp('15-MAY-22 10.59.11.532000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,0);
Insert into NGAN217.TBL_DONHANG_OLD (DONHANG_ID,SANPHAM_ID,SOLUONG,MAHANG,KHACHHANG_ID,NGAYTHANG,TINHTRANG,HUYDON) values (16,21,4,'6503',16,to_timestamp('15-MAY-22 10.59.11.540000000 AM','DD-MON-RR HH.MI.SSXFF AM'),0,0);
Insert into NGAN217.TBL_DONHANG_OLD (DONHANG_ID,SANPHAM_ID,SOLUONG,MAHANG,KHACHHANG_ID,NGAYTHANG,TINHTRANG,HUYDON) values (13,20,3,'4236',15,to_timestamp('14-MAY-22 03.31.53.507000000 PM','DD-MON-RR HH.MI.SSXFF AM'),0,0);
REM INSERTING into NGAN217.TBL_GIAODICH
SET DEFINE OFF;
REM INSERTING into NGAN217.TBL_GIAODICH_OLD
SET DEFINE OFF;
REM INSERTING into NGAN217.TBL_GIOHANG
SET DEFINE OFF;
REM INSERTING into NGAN217.TBL_GIOHANG1
SET DEFINE OFF;
REM INSERTING into NGAN217.TBL_GIOHANG_OLD
SET DEFINE OFF;
Insert into NGAN217.TBL_GIOHANG_OLD (GIOHANG_ID,TENSANPHAM,SANPHAM_ID,GIASANPHAM,HINHANH,SOLUONG) values (29,'ba lô cimima',31,'500000','balo4.jpg',1);
Insert into NGAN217.TBL_GIOHANG_OLD (GIOHANG_ID,TENSANPHAM,SANPHAM_ID,GIASANPHAM,HINHANH,SOLUONG) values (30,'quần jean titile goz',23,'1150000','quanjean1.jpg',1);
Insert into NGAN217.TBL_GIOHANG_OLD (GIOHANG_ID,TENSANPHAM,SANPHAM_ID,GIASANPHAM,HINHANH,SOLUONG) values (31,'áo sm khangu',19,'5600000','hot2.jpg',1);
Insert into NGAN217.TBL_GIOHANG_OLD (GIOHANG_ID,TENSANPHAM,SANPHAM_ID,GIASANPHAM,HINHANH,SOLUONG) values (32,'quần jean sehon',24,'600000','quanjean3.jpg',1);
REM INSERTING into NGAN217.TBL_KHACHHANG
SET DEFINE OFF;
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (21,'ABC','123123','shshaj','none','ABC@gmail.com','202cb962ac59075b964b07152d234b70',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (2,'Ngân Huỳnh','123123123','none',null,'admin@gmail.com','e10adc3949ba59abbe56e057f20f883e',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (3,'Ngân Huỳnh','123123123','none',null,'ngan123@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (4,'ngannnnn','123123123','none',null,'ngan@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (5,'test123','123123123','none',null,'test123@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (6,'abbbb','123123123','none',null,'ab@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (7,'accc','123123123','none',null,'ac@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (8,'ad','123123123','none',null,'ad@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (9,'aee','123123123','none',null,'ae@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (10,'af','123123123','none',null,'af@gmail.com','e10adc3949ba59abbe56e057f20f883e',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (11,'Ngân','123123123','none',null,'thanhngan@gmail.com','4df26b7d69a26516915261039bbb1cb6',0);
Insert into NGAN217.TBL_KHACHHANG (KHACHHANG_ID,NAME,PHONE,ADDRESS,NOTE,EMAIL,PASSWORD,GIAOHANG) values (12,'Ngân Huỳnh','123123123','none',null,'ngan145@gmail.com','e10adc3949ba59abbe56e057f20f883e',0);
REM INSERTING into NGAN217.TBL_SANPHAM
SET DEFINE OFF;
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (1,21,'Balo nam SP01',null,'Chất liệu : khum biết
Màu sắc : be
','400000','350000',0,0,45,'balo1.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (21,21,'Balo nam SP02','Balo nam th�?i trang 
','Chất liệu : Vải không dệt.
Màu sắc : �?�?','400000','350000',0,0,30,'balo6.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (22,21,'Balo nam SP03',null,'Chất liệu : Vải không dệt.
Màu sắc : đen','400000','380000',0,0,15,'hot19.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (28,62,'Balo Nữ SP12','Balo nữ th�?i trang','Chất liệu : Vải không dệt
Màu sắc : đ�?, cam, vàng, lục, lam, chàm, tím','350000','320000',0,0,45,'balo-nữ-hot-trend-đi-h�?c-cấp-3.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (25,62,'Balo Nữ SP11','Balo nữ th�?i trang','Chất liệu : Vải Simili (Vải giả da)','400000','350000',0,0,35,'balo2.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (29,62,'Balo nữ SP13','Balo nữ th�?i trang','Chất liệu : Vải giả da
Màu sắc : Hồng','200000','180000',0,0,30,'cac-mau-balo-dep-cho-nu-1.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (30,20,'Quần Kaki SP01',null,null,'180000','160000',0,0,30,'hot17.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (31,20,'Quần Kaki SP02',null,null,'200000','180000',0,0,15,'hot21.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (33,20,'Quần Kaki SP03',null,null,'200000','180000',0,0,15,'quantay1.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (34,19,'Quần Jean SP01',null,null,'200000','180000',0,0,50,'hot20.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (35,19,'Quần Jean SP02',null,null,'200000','180000',0,0,30,'hot13.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (36,19,'Quần Jean SP03',null,null,'280000','250000',0,0,50,'quanjean3.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (37,18,'�?o thun nam SP01',null,null,'200000','180000',0,0,30,'aothun1.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (39,18,'�?o thun nam SP02',null,null,'400000','380000',0,0,30,'download (1).jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (40,18,'�?o thun nam SP03',null,null,'350000','320000',0,0,30,'download.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (41,17,'�?o thun nữ SP01',null,null,'350000','320000',0,0,15,'Yellow.jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (42,17,'�?o thun nữ SP02',null,null,'350000','320000',0,0,50,'images (1).jpg');
Insert into NGAN217.TBL_SANPHAM (SANPHAM_ID,CATEGORY_ID,SANPHAM_NAME,SANPHAM_CHITIET,SANPHAM_MOTA,SANPHAM_GIA,SANPHAM_GIAKHUYENMAI,SANPHAM_ACTIVE,SANPHAM_HOT,SANPHAM_SOLUONG,SANPHAM_IMAGE) values (43,17,'�?o thun nữ SP03',null,null,'280000','250000',0,0,45,'images.jpg');
REM INSERTING into NGAN217.TBL_SLIDER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TBL_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_ADMIN_PK" ON "NGAN217"."TBL_ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BAIVIET_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_BAIVIET_PK1" ON "NGAN217"."TBL_BAIVIET" ("BAIVIET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_CATEGORY_PK" ON "NGAN217"."TBL_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DANHMUC_TIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_DANHMUC_TIN_PK" ON "NGAN217"."TBL_DANHMUC_TIN" ("DANHMUCTIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DONHANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_DONHANG_PK" ON "NGAN217"."TBL_DONHANG" ("DONHANG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GIAODICH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_GIAODICH_PK" ON "NGAN217"."TBL_GIAODICH" ("GIAODICH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GIOHANG_NEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_GIOHANG_NEW_PK" ON "NGAN217"."TBL_GIOHANG" ("KHACHHANG_ID", "SANPHAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GIOHANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_GIOHANG_PK" ON "NGAN217"."TBL_GIOHANG1" ("GIOHANG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_KHACHHANG_NEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_KHACHHANG_NEW_PK" ON "NGAN217"."TBL_KHACHHANG" ("KHACHHANG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SANPHAM_NEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_SANPHAM_NEW_PK" ON "NGAN217"."TBL_SANPHAM" ("SANPHAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SLIDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NGAN217"."TBL_SLIDER_PK" ON "NGAN217"."TBL_SLIDER" ("SLIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TBL_CATEGORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "NGAN217"."TBL_CATEGORY_TRG" 
BEFORE INSERT ON TBL_CATEGORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "NGAN217"."TBL_CATEGORY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_GIAODICH_OLD
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("GIAODICH_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("MAGIAODICH" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("NGAYTHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("TINHTRANGDON" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" MODIFY ("HUYDON" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH_OLD" ADD PRIMARY KEY ("GIAODICH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_KHACHHANG
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_KHACHHANG" ADD CONSTRAINT "TBL_KHACHHANG_NEW_PK" PRIMARY KEY ("KHACHHANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_GIOHANG
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("TENSANPHAM" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("GIAKHUYENMAI" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG" ADD CONSTRAINT "TBL_GIOHANG_NEW_PK" PRIMARY KEY ("KHACHHANG_ID", "SANPHAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NGAN217"."TBL_GIOHANG" MODIFY ("IMAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DONHANG_OLD
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("DONHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("MAHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("NGAYTHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("TINHTRANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" MODIFY ("HUYDON" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG_OLD" ADD PRIMARY KEY ("DONHANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SLIDER
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_SLIDER" MODIFY ("SLIDER_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SLIDER" MODIFY ("SLIDER_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SLIDER" MODIFY ("SLIDER_CAPTION" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SLIDER" MODIFY ("SLIDER_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SLIDER" ADD CONSTRAINT "TBL_SLIDER_PK" PRIMARY KEY ("SLIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ADMIN
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_ADMIN" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_ADMIN" MODIFY ("ADMIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_ADMIN" ADD CONSTRAINT "TBL_ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SANPHAM
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_NAME" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_GIA" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_GIAKHUYENMAI" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_HOT" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" MODIFY ("SANPHAM_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_SANPHAM" ADD CONSTRAINT "TBL_SANPHAM_NEW_PK" PRIMARY KEY ("SANPHAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DANHMUC_TIN
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_DANHMUC_TIN" MODIFY ("DANHMUCTIN_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DANHMUC_TIN" MODIFY ("TENDANHMUC" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DANHMUC_TIN" ADD CONSTRAINT "TBL_DANHMUC_TIN_PK" PRIMARY KEY ("DANHMUCTIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_BAIVIET
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("BAIVIET_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("TENBAIVIET" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("TOMTAT" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("NOIDUNG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("DANHMUCTIN_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" MODIFY ("BAIVIET_IMAGE" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_BAIVIET" ADD CONSTRAINT "TBL_BAIVIET_NEW_PK" PRIMARY KEY ("BAIVIET_ID")
  USING INDEX (CREATE UNIQUE INDEX "NGAN217"."TBL_BAIVIET_PK1" ON "NGAN217"."TBL_BAIVIET" ("BAIVIET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORY
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_CATEGORY" ADD CONSTRAINT "TBL_CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_GIOHANG_OLD
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("GIOHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("TENSANPHAM" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("GIASANPHAM" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("HINHANH" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG_OLD" ADD PRIMARY KEY ("GIOHANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_GIAODICH
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("GIAODICH_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("MAGIAODICH" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("NGAYTHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("TINHTRANGDON" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" MODIFY ("HUYDON" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIAODICH" ADD CONSTRAINT "TBL_GIAODICH_PK" PRIMARY KEY ("GIAODICH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DONHANG
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("DONHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" ADD CONSTRAINT "TBL_DONHANG_PK" PRIMARY KEY ("DONHANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("MAHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("NGAYTHANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("TINHTRANG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_DONHANG" MODIFY ("HUYDON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GIOHANG1
--------------------------------------------------------

  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("GIOHANG_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("TENSANPHAM" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("SANPHAM_ID" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("GIASANPHAM" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("HINHANH" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" ADD CONSTRAINT "TBL_GIOHANG_PK" PRIMARY KEY ("GIOHANG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NGAN217"."TBL_GIOHANG1" MODIFY ("KHACHHANG_ID" NOT NULL ENABLE);
